In [1]:
# 데이터 처리 및 분석
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import warnings

# 경로 설정
import os 
import sys

# 시각화
import matplotlib.pyplot as plt
import seaborn as sns

# 출력 설정
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

# 한글 폰트 설정
import platform
if platform.system() == 'Windows':
    plt.rcParams['font.family'] = 'Malgun Gothic'
elif platform.system() == 'Darwin':
    plt.rcParams['font.family'] = 'AppleGothic'
else:
    plt.rcParams['font.family'] = 'NanumGothic'

plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['figure.figsize'] = (12,6)

# 시드 설정
np.random.seed(42)

print('-' * 60)
print('라이브러리 로드 완료')
print('한글 폰트 설정 완료!')
print('-'* 60)

------------------------------------------------------------
라이브러리 로드 완료
한글 폰트 설정 완료!
------------------------------------------------------------

In [2]:
os.chdir(os.path.abspath('..'))
print(os.getcwd())

df = pd.read_csv('data/2025_Airbnb_NYC_listings.csv').drop(columns = 'Unnamed: 0')
df.head()

c:\workspace\camp\project\airbnb_price_prediction

,id,source,name,description,neighborhood_overview,host_id,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,36121,city scrape,Lg Rm in Historic Prospect Heights,Cozy space share in the heart of a great neigh...,Full of tree-lined streets and beautiful brown...,62165,Michael,2009-12-11,"New York, NY",I’m an urban planner working for an internatio...,NaN,NaN,NaN,f,Prospect Heights,1.0,3.0,"['email', 'phone', 'work_email']",t,t,Neighborhood highlights,Prospect Heights,Brooklyn,40.673760,-73.966110,Private room in rental unit,Private room,1,1.0,1 shared bath,1.0,1.0,"[""Refrigerator"", ""Dishes and silverware"", ""Wif...",$200.00,90,365,90.0,90.0,365.0,365.0,90.0,365.0,NaN,t,27,57,87,362,2025-03-03,9,0,0,301,0,0,0.0,2010-12-11,2013-05-10,4.88,5.00,4.80,5.00,5.00,5.00,5.00,NaN,f,1,0,1,0,0.05
1,36647,city scrape,"1 Bedroom & your own Bathroom, Elevator Apartment",Private bedroom with your own bathroom in a 2 ...,"Manhattan, SE corner of 2nd Ave/ E. 110th street",157798,Irene,2010-07-04,"New York, NY",NaN,NaN,NaN,100%,f,East Harlem,1.0,1.0,"['email', 'phone']",t,t,Neighborhood highlights,East Harlem,Manhattan,40.792454,-73.940742,Private room in condo,Private room,2,1.0,1 private bath,1.0,1.0,"[""Oven"", ""Blender"", ""Luggage dropoff allowed"",...",$82.00,30,999,30.0,30.0,999.0,999.0,30.0,999.0,NaN,t,0,0,0,204,2025-03-03,102,0,0,143,0,0,0.0,2010-10-04,2023-12-09,4.77,4.82,4.76,4.88,4.90,4.38,4.71,NaN,f,1,0,1,0,0.58
2,38663,city scrape,Luxury Brownstone in Boerum Hill,"Beautiful, large home in great hipster neighbo...","diverse, lively, hip, cool: loaded with restau...",165789,Sarah,2010-07-13,"New York, NY",I am a lawyer and work as an executive at an a...,within a few hours,100%,40%,f,Boerum Hill,1.0,3.0,"['email', 'phone', 'work_email']",t,t,Neighborhood highlights,Boerum Hill,Brooklyn,40.684420,-73.980680,Private room in home,Private room,2,2.5,2.5 baths,5.0,5.0,"[""Portable fans"", ""Oven"", ""Baking sheet"", ""Fir...",$765.00,3,60,3.0,3.0,60.0,60.0,3.0,60.0,NaN,t,30,49,66,326,2025-03-02,43,0,0,267,0,0,0.0,2012-07-09,2023-08-30,4.70,4.83,4.52,4.88,4.88,4.86,4.62,OSE-STRREG-0001784,f,1,0,1,0,0.28
3,38833,city scrape,Spectacular West Harlem Garden Apt,This is a very large and unique space. An inc...,West Harlem is now packed with great restauran...,166532,Matthew,2010-07-14,"New York, NY",I have been a New Yorker for a long time\n and...,within an hour,100%,97%,t,Harlem,1.0,1.0,"['email', 'phone']",t,t,Neighborhood highlights,Harlem,Manhattan,40.818058,-73.946671,Entire home,Entire home/apt,2,1.0,1 bath,1.0,1.0,"[""Fire extinguisher"", ""Clothing storage: close...",$139.00,2,45,2.0,2.0,1125.0,1125.0,2.0,1125.0,NaN,t,7,18,25,25,2025-03-03,241,42,3,25,43,255,35445.0,2010-08-28,2025-02-21,4.85,4.87,4.50,4.96,4.96,4.79,4.82,OSE-STRREG-0000476,f,1,1,0,0,1.36
4,39282,city scrape,“Work-from-home” from OUR home.,*Monthly Discount will automatically apply <br...,THE NEIGHBORHOOD:<br />Our apartment is locate...,168525,Gustavo,2010-07-16,"New York, NY",I am a music producer. And my wife is a hair s...,within an hour,100%,100%,t,Williamsburg,2.0,2.0,"['email', 'phone']",t,t,Neighborhood highlights,Williamsburg,Brooklyn,40.710651,-73.950874,Private room in rental unit,Private room,2,1.0,1 shared bath,1.0,1.0,"[""Oven"", ""Rice maker"", ""Laundromat nearby"", ""L...",$130.00,4,45,4.0,4.0,45.0,45.0,4.0,45.0,NaN,t,14,22,38,38,2025-03-02,274,12,0,38,12,154,20020.0,2010-08-02,2025-01-03,4.82,4.83,4.61,4.94,4.88,4.85,4.78,OSE-STRREG-0001150,f,2,0,2,0,1.54

### 1차 전처리

데이터에 필요 없는 칼럼 제거 및 논리에 맞게끔 칼럼 기본 형변환

In [3]:
# 분석에 의미없는 칼럼 제거(단일값 및 스크랩 시점 등)
drop_cols = ['source','calendar_updated','calendar_last_scraped']

# t,f -> True/False로 변환
convert_tf_cols = ['host_is_superhost', 'host_has_profile_pic',
                'host_identity_verified','has_availability',
                'instant_bookable']

# $2,000 -> 2000으로 변환
df['price'] = df['price'].str.replace('$','').str.replace(',','').astype('float')

# 날짜 type으로 변환
df['host_since'] = pd.to_datetime(df['host_since'])
df['first_review'] = pd.to_datetime(df['first_review'])
df['last_review'] = pd.to_datetime(df['last_review'])

# 99% -> 0.99로 변환
df['host_response_rate'] = df['host_response_rate'].str.replace('%','').astype('float') / 100
df['host_acceptance_rate'] = df['host_acceptance_rate'].str.replace('%','').astype('float')  / 100

# 처리 함수
def convert_tf(df, cols):
    for col in cols:
        df[col] = df[col].map({'t':True, 'f':False}).astype('boolean')

    return df

df_cleaned = convert_tf(df, convert_tf_cols)
df_cleaned = df_cleaned.drop(columns = drop_cols)

'['email','phone','work_email']'과 같이 리스트가 string형태로 저장

-> 원-핫 인코딩으로 데이터 변환

In [4]:
import ast
from sklearn.preprocessing import MultiLabelBinarizer

df_cleaned.loc[df['host_verifications'].isna(),'host_verifications'] = '[]'

# '['email','phone']'과 같이 리스트가 string형태로 저장 -> list로 변환
df_cleaned['host_verifications'] = df_cleaned['host_verifications'].apply(ast.literal_eval)

# Multilabelbinarizier 사용
mlb = MultiLabelBinarizer()

# 리스트 데이터를 0,1로 변환
verifications_encoded = mlb.fit_transform(df_cleaned['host_verifications'])

verifications_encoded

array([[1, 1, 1],
       [1, 1, 0],
       [1, 1, 1],
       ...,
       [1, 1, 1],
       [1, 1, 0],
       [1, 1, 0]], shape=(22308, 3))

In [5]:
# 원-핫 인코딩 저장 정보를 df에 저장
for i, c in enumerate(mlb.classes_):
    col_name = 'host_verifications_' + c
    df_cleaned[col_name] = verifications_encoded[:,i]

df_cleaned = df_cleaned.drop(columns = 'host_verifications')
display(df_cleaned.iloc[:,-3:].head())

,host_verifications_email,host_verifications_phone,host_verifications_work_email
0,1,1,1
1,1,1,0
2,1,1,1
3,1,1,0
4,1,1,0

In [6]:
df_cleaned['log_price'] = np.log(df_cleaned['price'] + 1)
df_cleaned['log_estimated_revenue_l365d'] = np.log(df['estimated_revenue_l365d'] + 1)

In [7]:
df_cleaned.to_csv('data/df_cleaned.csv', index = False)

In [1]:
df.shape()

NameError: name 'df' is not defined