In [1]:
# 데이터 처리 및 분석
import pandas as pd
import numpy as np
import warnings

# 경로 설정
import os 
import sys

# 시각화
import matplotlib.pyplot as plt
import seaborn as sns

# 모델링
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# 평가지표
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# 출력 설정
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 150)

# 한글 폰트 설정
import platform
if platform.system() == 'Windows':
    plt.rcParams['font.family'] = 'Malgun Gothic'
elif platform.system() == 'Darwin':
    plt.rcParams['font.family'] = 'AppleGothic'
else:
    plt.rcParams['font.family'] = 'NanumGothic'

plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['figure.figsize'] = (12,6)

# 시드 설정
np.random.seed(42)
random_seed = 42

print('-' * 60)
print('라이브러리 로드 완료')
print('한글 폰트 설정 완료!')
print('-'* 60)

------------------------------------------------------------
라이브러리 로드 완료
한글 폰트 설정 완료!
------------------------------------------------------------

- 추후 LabelEncoding 사용할 변수

host_is_superhost, host_has_profile_pic

- 추후 원-핫 인코딩 사용해야할 변수

property_type, room_type

In [2]:
os.chdir(os.path.abspath('..'))
print(os.getcwd())

df = pd.read_csv('data/df_use_modeling.csv')
df.head()

c:\workspace\camp\project\airbnb_price_prediction

,id,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_identity_verified,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,room_type,accommodates,bathrooms,bedrooms,beds,price,off_peak_min,peak_min,peak_max,off_peak_max,availability_30,availability_90,number_of_reviews,number_of_reviews_l30d,estimated_occupancy_l365d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,log_price,has_self_checkin,has_wifi,has_kitchen,has_dryer,has_air_conditioning,has_heating,has_dedicated_workspace,has_hair_dryer,has_iron,has_gym,has_bbq_grill,has_breakfast,has_fireplace,has_smoking_allowed,has_pets_allowed,has_wine_glasses,has_crib,has_city_skyline_view,has_river_view,has_luggage_dropoff_allowed,has_long_term_stays_allowed,has_private_entrance,has_exterior_security_cameras,has_elevator,has_lock_on_bedroom_door,has_tub,has_washer,has_pool,has_alarm,has_garden_courtyard_view,has_outdoor,has_free_parking,amenities_count,count_appliances_expensive,has_ott,host_experience_months,log_competition_count_1000m,inner_500_devided_1000,host_non_exposure,property_grouped,hosting_period,calculated_entire_rate,calculated_private_rate,calculated_shared_rate
0,5.305079e+07,1.0,1.0,1.0,0.94,True,True,Tottenville,Staten Island,40.504560,-74.249840,Entire home/apt,2.0,1.0,1.0,1.0,92.0,30.0,30.0,160.0,160.0,0.0,31.0,47.0,0.0,120.0,4.72,4.74,4.83,4.87,4.62,0,1,1.0,4.532599,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,46.0,4.0,1.0,104.0,0.693147,0.0,0,House,40.0,1.0,0.0,0.0
1,6.391990e+05,1.0,1.0,1.0,0.50,False,True,Tottenville,Staten Island,40.508630,-74.241350,Entire home/apt,8.0,4.5,4.0,6.0,165.0,30.0,30.0,365.0,365.0,0.0,42.0,105.0,0.0,0.0,4.92,4.97,4.99,4.68,4.85,0,1,1.0,5.111988,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,38.0,6.0,0.0,159.0,1.098612,0.0,1,House,139.0,1.0,0.0,0.0
2,6.614040e+17,1.0,0.0,NaN,NaN,False,True,Tottenville,Staten Island,40.500366,-74.239401,Private room,2.0,1.0,1.0,1.0,105.0,2.0,2.0,730.0,730.0,29.0,89.0,56.0,0.0,0.0,4.98,5.00,4.96,4.91,4.91,1,1,1.0,4.663439,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,47.0,4.0,0.0,96.0,0.693147,0.0,0,House,32.0,0.0,1.0,0.0
3,1.297921e+18,1.0,1.0,1.0,1.00,True,True,Tottenville,Staten Island,40.520100,-74.230910,Entire home/apt,2.0,1.0,1.0,1.0,66.0,1.0,1.0,21.0,21.0,13.0,54.0,5.0,3.0,64.0,5.00,5.00,5.00,5.00,5.00,1,1,1.0,4.204693,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,29.0,0.0,0.0,92.0,0.000000,0.0,0,House,2.0,1.0,0.0,0.0
4,6.239119e+17,NaN,1.0,1.0,0.80,True,True,Prince's Bay,Staten Island,40.524980,-74.215140,Entire home/apt,4.0,2.0,2.0,3.0,171.0,30.0,30.0,1125.0,1125.0,0.0,0.0,28.0,0.0,120.0,4.89,4.93,5.00,4.89,4.71,0,1,1.0,5.147494,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,50.0,3.0,1.0,34.0,1.098612,0.0,1,Apartment,34.0,1.0,0.0,0.0

- id, neighbourhood_cleansed, latitude, longitude는 향후 해석시에 용이하게 활용하기 위해 남겨둠

In [3]:
df.select_dtypes('object').columns

Index(['host_is_superhost', 'host_identity_verified', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'room_type', 'property_grouped'],
      dtype='str')

In [4]:
df.loc[df['neighbourhood_group_cleansed'].isin(['Queens','Bronx','Staten Island']), 
    'neighbourhood_group_cleansed'] = 'Other'

In [5]:
id_vals = ['id','latitude','longitude','neighbourhood_cleansed','neighbourhood_group_cleansed'
        ,'price']
label_cols = ['host_is_superhost','neighbourhood_group_cleansed','host_identity_verified']
dummy_cols = ['room_type', 'property_grouped']

In [6]:
df['neighbourhood_group_cleansed'].value_counts()

neighbourhood_group_cleansed
Manhattan    6176
Brooklyn     5336
Other        3272
Name: count, dtype: int64

In [7]:
map_dict = {'Manhattan':1, 'Brooklyn':2, 'Other':3}

for col in label_cols:
    le = LabelEncoder()
    if col != 'neighbourhood_group_cleansed':
        df[col] = le.fit_transform(df[col])
    else:
        df['city'] = df[col].map(lambda x: map_dict[x])

In [8]:
df = pd.get_dummies(df, columns = dummy_cols, drop_first = True)
df.head()

,id,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_identity_verified,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,accommodates,bathrooms,bedrooms,beds,price,off_peak_min,peak_min,peak_max,off_peak_max,availability_30,availability_90,number_of_reviews,number_of_reviews_l30d,estimated_occupancy_l365d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,log_price,has_self_checkin,has_wifi,has_kitchen,has_dryer,has_air_conditioning,has_heating,has_dedicated_workspace,has_hair_dryer,has_iron,has_gym,has_bbq_grill,has_breakfast,has_fireplace,has_smoking_allowed,has_pets_allowed,has_wine_glasses,has_crib,has_city_skyline_view,has_river_view,has_luggage_dropoff_allowed,has_long_term_stays_allowed,has_private_entrance,has_exterior_security_cameras,has_elevator,has_lock_on_bedroom_door,has_tub,has_washer,has_pool,has_alarm,has_garden_courtyard_view,has_outdoor,has_free_parking,amenities_count,count_appliances_expensive,has_ott,host_experience_months,log_competition_count_1000m,inner_500_devided_1000,host_non_exposure,hosting_period,calculated_entire_rate,calculated_private_rate,calculated_shared_rate,city,room_type_Hotel room,room_type_Private room,room_type_Shared room,property_grouped_Hospitality,property_grouped_House,property_grouped_Other
0,5.305079e+07,1.0,1.0,1.0,0.94,1,1,Tottenville,Other,40.504560,-74.249840,2.0,1.0,1.0,1.0,92.0,30.0,30.0,160.0,160.0,0.0,31.0,47.0,0.0,120.0,4.72,4.74,4.83,4.87,4.62,0,1,1.0,4.532599,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,46.0,4.0,1.0,104.0,0.693147,0.0,0,40.0,1.0,0.0,0.0,3,False,False,False,False,True,False
1,6.391990e+05,1.0,1.0,1.0,0.50,0,1,Tottenville,Other,40.508630,-74.241350,8.0,4.5,4.0,6.0,165.0,30.0,30.0,365.0,365.0,0.0,42.0,105.0,0.0,0.0,4.92,4.97,4.99,4.68,4.85,0,1,1.0,5.111988,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,38.0,6.0,0.0,159.0,1.098612,0.0,1,139.0,1.0,0.0,0.0,3,False,False,False,False,True,False
2,6.614040e+17,1.0,0.0,NaN,NaN,0,1,Tottenville,Other,40.500366,-74.239401,2.0,1.0,1.0,1.0,105.0,2.0,2.0,730.0,730.0,29.0,89.0,56.0,0.0,0.0,4.98,5.00,4.96,4.91,4.91,1,1,1.0,4.663439,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,47.0,4.0,0.0,96.0,0.693147,0.0,0,32.0,0.0,1.0,0.0,3,False,True,False,False,True,False
3,1.297921e+18,1.0,1.0,1.0,1.00,1,1,Tottenville,Other,40.520100,-74.230910,2.0,1.0,1.0,1.0,66.0,1.0,1.0,21.0,21.0,13.0,54.0,5.0,3.0,64.0,5.00,5.00,5.00,5.00,5.00,1,1,1.0,4.204693,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,29.0,0.0,0.0,92.0,0.000000,0.0,0,2.0,1.0,0.0,0.0,3,False,False,False,False,True,False
4,6.239119e+17,NaN,1.0,1.0,0.80,1,1,Prince's Bay,Other,40.524980,-74.215140,4.0,2.0,2.0,3.0,171.0,30.0,30.0,1125.0,1125.0,0.0,0.0,28.0,0.0,120.0,4.89,4.93,5.00,4.89,4.71,0,1,1.0,5.147494,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,50.0,3.0,1.0,34.0,1.098612,0.0,1,34.0,1.0,0.0,0.0,3,False,False,False,False,False,False

In [9]:
missing_col = df.columns[df.isna().sum() > 0]
df[missing_col].isna().sum() / len(df)

host_location             0.235390
host_response_rate        0.162135
host_acceptance_rate      0.109240
bathrooms                 0.000271
bedrooms                  0.001691
beds                      0.004464
host_experience_months    0.001285
hosting_period            0.030777
dtype: float64

나머지 변수들은 전체 데이터의 20% 이하의 결측치를 보이므로 단순 대체

host location의 경우, 정보 미기입의 의미로 4로 표기

In [10]:
df.loc[df['host_location'].isna(),'host_location'] = 4

자치구 데이터로 분할

맨해튼, 브루클린, 그 외

In [11]:
X = df.drop(columns = ['log_price'])
y = df['log_price']

# 1. 공통(전체)
X_train_all, X_test_all, y_train_all, y_test_all = train_test_split(X, y, test_size=0.2, random_state=random_seed, stratify = df['city'])

# 이상치 클리핑
q1, q3 = y_train_all.quantile([0.25, 0.75])
iqr = q3 - q1
lower, upper = q1 - 1.5 * iqr, q3 + 1.5 * iqr

train_upper_count = (y_train_all > upper).sum()
train_lower_count = (y_train_all < lower).sum()

test_upper_count = (y_test_all > upper).sum()
test_lower_count = (y_test_all < lower).sum()

print(f"[Train] 상한 초과: {train_upper_count}개 ({train_upper_count/len(y_train_all)*100:.2f}%)")
print(f"[Train] 하한 미만: {train_lower_count}개 ({train_lower_count/len(y_train_all)*100:.2f}%)")
print(f"[Test]  상한 초과: {test_upper_count}개 ({test_upper_count/len(y_test_all)*100:.2f}%)")
print(f"[Test]  하한 미만: {test_lower_count}개 ({test_lower_count/len(y_test_all)*100:.2f}%)")

y_train_all = y_train_all.clip(lower = lower)
y_test_all = y_test_all.clip(lower = lower)

train_keep_mask = y_train_all <= upper
test_keep_mask = y_test_all <= upper

X_train_all = X_train_all[train_keep_mask]
y_train_all = y_train_all[train_keep_mask]

X_test_all = X_test_all[test_keep_mask]
y_test_all = y_test_all[test_keep_mask]

def get_city_data(X_train, y_train, X_test, y_test, city_code):
    
    X_tr = X_train[X_train['city'] == city_code].copy()
    y_tr = y_train[X_train['city'] == city_code].copy()
    X_te = X_test[X_test['city'] == city_code].copy()
    y_te = y_test[X_test['city'] == city_code].copy()
    
    # 'city' 컬럼 삭제
    X_tr = X_tr.drop(columns=['city'])
    X_te = X_te.drop(columns=['city'])

    return X_tr, y_tr, X_te, y_te

# --- 1. 자치구별로 데이터 쪼개기 ---
# Manhattan (1) - mnh 유지
X_train_mnh, y_train_mnh, X_test_mnh, y_test_mnh = \
    get_city_data(X_train_all, y_train_all, X_test_all, y_test_all, 1)

# Brooklyn (2) - bkl 유지
X_train_bkl, y_train_bkl, X_test_bkl, y_test_bkl = \
    get_city_data(X_train_all, y_train_all, X_test_all, y_test_all, 2)

# Other (3) - other로 풀기
X_train_other, y_train_other, X_test_other, y_test_other = \
    get_city_data(X_train_all, y_train_all, X_test_all, y_test_all, 3)

[Train] 상한 초과: 200개 (1.69%)
[Train] 하한 미만: 5개 (0.04%)
[Test]  상한 초과: 44개 (1.49%)
[Test]  하한 미만: 2개 (0.07%)

각각의 데이터에 대해, 결측치 대체 및 종속변수 상한/하한선 조정

In [12]:
def preprocess_data(X_train, y_train ,X_test, y_test, missing_cols, id_vals):
    '''
    Train 데이터를 기준으로 통계값을 계산하고 Test 데이터에 동일하게 적용
    '''
    
    # 1. 단순 대체
    for col in missing_cols[1:]:
        if X_train[col].dtype.name in ['float64', 'int64']:
            fill_val = X_train[col].median()
            X_train[col] = X_train[col].fillna(fill_val)
            X_test[col] = X_test[col].fillna(fill_val)
        else:
            fill_val = X_train[col].mode()[0]
            X_train[col] = X_train[col].fillna(fill_val)
            X_test[col] = X_test[col].fillna(fill_val)

    # 2. ID 및 위치 정보 분리 및 삭제
    train_id_vals = X_train[id_vals]
    test_id_vals = X_test[id_vals]
    
    X_train = X_train.drop(columns = id_vals)
    X_test = X_test.drop(columns = id_vals)

    return X_train, y_train, X_test, y_test, train_id_vals, test_id_vals

# 1. 맨해튼 (mnh)
X_train_mnh, y_train_mnh, X_test_mnh, y_test_mnh, ids_train_mnh, ids_test_mnh = \
    preprocess_data(X_train_mnh, y_train_mnh, X_test_mnh, y_test_mnh, missing_col, id_vals)
print(f"[Manhattan] Train: {X_train_mnh.shape}, Test: {X_test_mnh.shape}")

# 2. 브루클린 (bkl)
X_train_bkl, y_train_bkl, X_test_bkl, y_test_bkl, ids_train_bkl, ids_test_bkl = \
    preprocess_data(X_train_bkl, y_train_bkl, X_test_bkl, y_test_bkl, missing_col, id_vals)
print(f"[Brooklyn]  Train: {X_train_bkl.shape}, Test: {X_test_bkl.shape}")

# 3. 기타 (other)
X_train_other, y_train_other, X_test_other, y_test_other, ids_train_other, ids_test_other = \
    preprocess_data(X_train_other, y_train_other, X_test_other, y_test_other, missing_col, id_vals)
print(f"[Other]     Train: {X_train_other.shape}, Test: {X_test_other.shape}")

# 4. 전체 (total)
X_train_all, y_train_all, X_test_all, y_test_all, ids_train_all, ids_test_all = \
    preprocess_data(X_train_all, y_train_all, X_test_all, y_test_all, missing_col, id_vals)
print(f"[Total]     Train: {X_train_all.shape}, Test: {X_test_all.shape}")

print("모든 데이터 세트 전처리 완료 및 ID 분리 성공!")

[Manhattan] Train: (4783, 76), Test: (1202, 76)
[Brooklyn]  Train: (4234, 76), Test: (1059, 76)
[Other]     Train: (2610, 76), Test: (652, 76)
[Total]     Train: (11627, 77), Test: (2913, 77)
모든 데이터 세트 전처리 완료 및 ID 분리 성공!

In [13]:
X_train_all.to_csv('data/all/X_train_all.csv', index = False)
y_train_all.to_csv('data/all/y_train_all.csv', index = False)
X_test_all.to_csv('data/all/X_test_all.csv', index = False)
y_test_all.to_csv('data/all/y_test_all.csv', index = False)
ids_train_all.to_csv('data/all/ids_train_all.csv', index = False)
ids_test_all.to_csv('data/all/ids_test_all.csv', index = False)

In [14]:
X_train_mnh.to_csv('data/manhattan/X_train_mnh.csv', index = False)
y_train_mnh.to_csv('data/manhattan/y_train_mnh.csv', index = False)
X_test_mnh.to_csv('data/manhattan/X_test_mnh.csv', index = False)
y_test_mnh.to_csv('data/manhattan/y_test_mnh.csv', index = False)
ids_train_mnh.to_csv('data/manhattan/ids_train_mnh.csv', index = False)
ids_test_mnh.to_csv('data/manhattan/ids_test_mnh.csv', index = False)

In [15]:
X_train_bkl.to_csv('data/brooklyn/X_train_bkl.csv', index = False)
y_train_bkl.to_csv('data/brooklyn/y_train_bkl.csv', index = False)
X_test_bkl.to_csv('data/brooklyn/X_test_bkl.csv', index = False)
y_test_bkl.to_csv('data/brooklyn/y_test_bkl.csv', index = False)
ids_train_bkl.to_csv('data/brooklyn/ids_train_bkl.csv', index = False)
ids_test_bkl.to_csv('data/brooklyn/ids_test_bkl.csv', index = False)

In [16]:
X_train_other.to_csv('data/other/X_train_other.csv', index = False)
y_train_other.to_csv('data/other/y_train_other.csv', index = False)
X_test_other.to_csv('data/other/X_test_other.csv', index = False)
y_test_other.to_csv('data/other/y_test_other.csv', index = False)
ids_train_other.to_csv('data/other/ids_train_other.csv', index = False)
ids_test_other.to_csv('data/other/ids_test_other.csv', index = False)