In [2]:
import os

os.getcwd()

'd:\\Dev\\airbnb_price_prediction\\notebooks'

In [3]:
import pandas as pd

df_cleaned = pd.read_csv("../data/df_cleaned.csv")

In [4]:
# 리뷰 관련 컬럼 리스트로
review_columns = [
    "number_of_reviews",
    "reviews_per_month",
    "number_of_reviews_ltm",
    "number_of_reviews_l30d",
    "number_of_reviews_ly",
    "first_review",
    "last_review",
    "review_scores_rating",
    "review_scores_accuracy",
    "review_scores_cleanliness",
    "review_scores_checkin",
    "review_scores_communication",
    "review_scores_location",
    "review_scores_value",
]

df_reviews = df_cleaned[review_columns]

display(df_reviews.head())

,number_of_reviews,reviews_per_month,number_of_reviews_ltm,number_of_reviews_l30d,number_of_reviews_ly,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
0,9,0.05,0,0,0,2010-12-11,2013-05-10,4.88,5.00,4.80,5.00,5.00,5.00,5.00
1,102,0.58,0,0,0,2010-10-04,2023-12-09,4.77,4.82,4.76,4.88,4.90,4.38,4.71
2,43,0.28,0,0,0,2012-07-09,2023-08-30,4.70,4.83,4.52,4.88,4.88,4.86,4.62
3,241,1.36,42,3,43,2010-08-28,2025-02-21,4.85,4.87,4.50,4.96,4.96,4.79,4.82
4,274,1.54,12,0,12,2010-08-02,2025-01-03,4.82,4.83,4.61,4.94,4.88,4.85,4.78

In [5]:
# 리뷰 컬럼별 결측치 개수
print(df_reviews.isnull().sum())

# 결측치 비율로
reviews_missing_ratio = (df_reviews.isnull().sum() / len(df_reviews)) * 100
print(reviews_missing_ratio.round(2))

number_of_reviews                 0
reviews_per_month              6798
number_of_reviews_ltm             0
number_of_reviews_l30d            0
number_of_reviews_ly              0
first_review                   6798
last_review                    6798
review_scores_rating           6798
review_scores_accuracy         6798
review_scores_cleanliness      6798
review_scores_checkin          6798
review_scores_communication    6798
review_scores_location         6799
review_scores_value            6798
dtype: int64
number_of_reviews               0.00
reviews_per_month              30.47
number_of_reviews_ltm           0.00
number_of_reviews_l30d          0.00
number_of_reviews_ly            0.00
first_review                   30.47
last_review                    30.47
review_scores_rating           30.47
review_scores_accuracy         30.47
review_scores_cleanliness      30.47
review_scores_checkin          30.47
review_scores_communication    30.47
review_scores_location         30.48
review_scores_value            30.47
dtype: float64

In [6]:
# 결측치 원인
no_reviews_count = (df_reviews["number_of_reviews"] == 0).sum()
print(f"리뷰가 없는 숙소의 수: {no_reviews_count}개")

리뷰가 없는 숙소의 수: 6798개

## 리뷰 관련 컬럼 결측치 처리

In [7]:
# df_reviews_cleaned 에 리뷰 컬럼 모음 복사본 저장
df_reviews_cleaned = df_reviews.copy()

# 월별 리뷰 수 결측치 0(리뷰 없음)으로 채우기
df_reviews_cleaned[["reviews_per_month"]] = df_reviews_cleaned[["reviews_per_month"]].fillna(0)

# 평점 관련 컬럼 필터링
score_columns = df_reviews_cleaned.filter(like="review_scores").columns

# 각 평점 컬럼 결측치 0(리뷰 없음)으로 채우기
df_reviews_cleaned[score_columns] = df_reviews_cleaned[score_columns].fillna(0)

# 날짜 관련 결측치 "리뷰 없음"으로 채우기
df_reviews_cleaned[["first_review", "last_review"]] = df_reviews_cleaned[["first_review", "last_review"]].fillna(
    "No Review"
)

print(df_reviews_cleaned.isna().sum())

number_of_reviews              0
reviews_per_month              0
number_of_reviews_ltm          0
number_of_reviews_l30d         0
number_of_reviews_ly           0
first_review                   0
last_review                    0
review_scores_rating           0
review_scores_accuracy         0
review_scores_cleanliness      0
review_scores_checkin          0
review_scores_communication    0
review_scores_location         0
review_scores_value            0
dtype: int64

In [8]:
# 날짜 결측치 -> 리뷰 없음 확인
df_reviews_cleaned[["first_review", "last_review"]]

      first_review last_review
0       2010-12-11  2013-05-10
1       2010-10-04  2023-12-09
2       2012-07-09  2023-08-30
3       2010-08-28  2025-02-21
4       2010-08-02  2025-01-03
...            ...         ...
22303    No Review   No Review
22304    No Review   No Review
22305    No Review   No Review
22306    No Review   No Review
22307    No Review   No Review

[22308 rows x 2 columns]

In [11]:
df_reviews_cleaned.to_csv('../data/df_reviews_cleaned.csv', index = False)